version: '3.8'

services:
  web:
    image: axenedu/django-prod-server:lastest
    container_name: djangogirls-prod-server
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.prod
    command: gunicorn mysite.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/django/mysite/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env/.env.prod
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env/.env.prod.db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/django/mysite/staticfiles
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
