version: '3.8'

services:
  web:
    image: django-dev-server:lastest
    container_name: djangogirls-dev-server
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
  db:
    image: postgres:15
    container_name: djangogirls-dev-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev.postgres

volumes:
  postgres_data:
