apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
  labels:
    app: polls
spec:
	replicas: 2
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
        - image: axenedu/django-prod-server:latest
          name: django
          envFrom:
          - secretRef:
              name: django-secret
          - configMapRef:
              name: django-config
          ports:
            - containerPort: 8000
              name: gunicorn
          env:
            - name: SQL_HOST
              value: "pgsql-service"