apiVersion: v1
kind: Service
metadata:
  name: pgsql-service
  labels:
    app: djangogirls
    type: database
spec:
  selector:
    app: djangogirls
    type: database
  ports:
  - port: 5432
    targetPort: db-port
  type: ClusterIP